<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Nesting extends Component
{
    public $data_card = [
        [
            "title" => "Kancil Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ],
        [
            "title" => "Tikus Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ],
        [
            "title" => "Macan Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ],
        [
            "title" => "Lumba lumba Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ],
        [
            "title" => "Kucing Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ],
        [
            "title" => "Tom  Anak Baik",
            "desc" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi ex quae velit dolor neque deserunt voluptates eum quam eveniet harum dolorem, iste, maxime aliquid. Quasi velit veniam similique ratione ipsa natus, sunt, ea, consectetur placeat fugit explicabo ipsam recusandae maxime at. Inventore commodi, iste eaque est voluptatem minus sapiente distinctio incidunt dolorum praesentium molestias ut cumque ipsa exercitationem odio qui laudantium suscipit a ipsam expedita natus reiciendis quasi aperiam vero? Animi rem veritatis inventore? Quidem, est sequi. Provident adipisci, qui veniam accusamus velit a quos ut mollitia natus, debitis animi vel illum facere harum ratione porro nam eos asperiores est. Saepe architecto reiciendis perspiciatis illo, culpa tenetur voluptatibus repudiandae dolores earum eos labore, quia consectetur ab quam exercitationem, neque enim. Dolore assumenda beatae illo consequatur, deserunt nihil architecto aliquid est saepe nam natus quae. Iusto quis est, molestiae eligendi, nostrum saepe corrupti sit quae optio maxime, dolores amet ab accusamus voluptatum fugit quibusdam? Laudantium animi vitae deleniti a excepturi dolorum nesciunt sit, nostrum facilis maiores earum. Eos, quas accusamus quibusdam illo quam magni odit placeat expedita, error omnis necessitatibus itaque voluptate. Nihil est omnis quibusdam id tenetur a suscipit iusto, nostrum nisi enim consectetur ducimus, veniam natus possimus quasi repudiandae",
        ]
    ];

    public function render()
    {
        return view('livewire.nesting');
    }
}
